"""Pull requests and deletion proposals - the human approval boundary.

GoldenFlow never commits to a protected branch. Everything it produces arrives as a
pull request a person approves, and every PR carries the evidence needed to approve
or reject it without re-deriving anything.

Two flows, deliberately asymmetric:

**Additions** need one signal: a validated test closing a real gap. The downside of a
wrong addition is a redundant test.

**Deletions need two independent signals plus a registry check.** Traffic alone is
never enough - it is inverted for exactly the low-volume, high-consequence flows that
matter most. The downside of a wrong deletion is silently losing the coverage that
was protecting a regulatory obligation, and nobody finds out until it fails.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Sequence

from goldenflow.phase0.registry import ProtectedTestRegistry
from goldenflow.phase5.validation import ValidationResult, Verdict


class ChangeKind(str, Enum):
    ADD = "add"
    UPDATE = "update"
    DELETE = "delete"


@dataclass
class ProposedChange:
    kind: ChangeKind
    path: str
    test_name: str
    body: str = ""
    rationale: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind.value,
            "path": self.path,
            "test_name": self.test_name,
            "rationale": self.rationale,
            "evidence": self.evidence,
        }


@dataclass
class PullRequest:
    """A proposal, never a commit."""

    title: str
    branch: str
    changes: list[ProposedChange] = field(default_factory=list)
    base: str = "main"
    labels: list[str] = field(default_factory=list)
    draft: bool = False

    @property
    def is_empty(self) -> bool:
        return not self.changes

    def body(self) -> str:
        """The PR description. Written for the reviewer, not for a changelog."""
        additions = [c for c in self.changes if c.kind is ChangeKind.ADD]
        updates = [c for c in self.changes if c.kind is ChangeKind.UPDATE]
        deletions = [c for c in self.changes if c.kind is ChangeKind.DELETE]

        lines = [
            "## What this changes",
            "",
            f"- {len(additions)} test(s) added",
            f"- {len(updates)} test(s) updated",
            f"- {len(deletions)} deletion(s) proposed",
            "",
            "Generated by GoldenFlow from production telemetry. Every test below ran "
            "green on a real device before this PR was opened - see the evidence "
            "per test.",
            "",
        ]

        if additions:
            lines += ["## Added", ""]
            for change in additions:
                evidence = change.evidence
                lines += [
                    f"### `{change.test_name}`",
                    "",
                    f"{change.rationale}",
                    "",
                    f"| | |",
                    f"|---|---|",
                    f"| Journey | `{evidence.get('journey_id', '-')}` "
                    f"{evidence.get('journey_name', '')} |",
                    f"| Production traffic | {evidence.get('sessions', 0):,} sessions "
                    f"({evidence.get('session_share_pct', 0)}%) |",
                    f"| Journey score | {evidence.get('score', 0)} |",
                    f"| Failure signals | {evidence.get('risk_events', 0)} |",
                    f"| Validation | {evidence.get('runs', 0)} runs across "
                    f"{evidence.get('profiles', 0)} device profiles, "
                    f"{evidence.get('pass_rate', 0)}% pass |",
                    f"| Locator sources | {', '.join(evidence.get('locator_sources', []))} |",
                    "",
                ]

        if deletions:
            lines += [
                "## Deletions proposed",
                "",
                "**Each requires two independent signals and your approval.** "
                "Traffic alone is never sufficient - it is inverted for the "
                "low-volume, high-consequence flows that matter most.",
                "",
            ]
            for change in deletions:
                lines += [
                    f"### `{change.test_name}`",
                    "",
                    f"{change.rationale}",
                    "",
                    f"Signals: {', '.join(change.evidence.get('signals', []))}",
                    "",
                ]

        lines += [
            "---",
            "",
            "Review checklist:",
            "",
            "- [ ] The journey matches what users actually do",
            "- [ ] Assertions would catch a real regression, not just navigation",
            "- [ ] Locators match the team's conventions",
            "- [ ] No deletion removes coverage you rely on",
        ]
        return "\n".join(lines)

    def to_payload(self, repo: str = "") -> dict[str, Any]:
        """The body for POST /repos/{owner}/{repo}/pulls."""
        return {
            "repo": repo,
            "title": self.title,
            "head": self.branch,
            "base": self.base,
            "body": self.body(),
            "draft": self.draft,
            "labels": self.labels,
            "files": [
                {"path": c.path, "content": c.body, "operation": c.kind.value}
                for c in self.changes
            ],
        }

    def write(self, path: str | Path, *, repo: str = "") -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(self.to_payload(repo), indent=2), encoding="utf-8")
        return target


def build_pull_request(
    validated: Sequence[ValidationResult],
    *,
    target_dir: str = "tests/generated",
    branch: str = "goldenflow/generated-tests",
) -> PullRequest:
    """Assemble a PR from validated tests only.

    Anything not carrying :attr:`Verdict.VALIDATED` is excluded here rather than
    filtered later, so there is no code path in which an unvalidated test reaches a
    reviewer.
    """
    pr = PullRequest(
        title="[GoldenFlow] Add tests for uncovered production journeys",
        branch=branch,
        labels=["goldenflow", "generated", "needs-review"],
    )

    for result in validated:
        if result.verdict is not Verdict.VALIDATED:
            continue
        spec = result.test.spec
        provenance = spec.provenance
        pr.changes.append(ProposedChange(
            kind=ChangeKind.ADD,
            path=f"{target_dir}/{spec.test_name}.py",
            test_name=spec.test_name,
            body=result.test.code,
            rationale=(
                f"Covers a production journey with no existing test coverage."
                + (f" {provenance.sessions:,} sessions "
                   f"({provenance.session_share_pct}% of traffic)."
                   if provenance else "")
                + (" Touches a screen the taxonomy marks critical."
                   if spec.touches_critical else "")
            ),
            evidence={
                **(provenance.to_dict() if provenance else {}),
                "runs": len(result.executed_runs),
                "profiles": len(result.profiles),
                "pass_rate": result.pass_rate,
            },
        ))

    if any(c.evidence.get("risk_events") for c in pr.changes):
        pr.labels.append("critical-screen")
    return pr


# --------------------------------------------------------------- deletions


@dataclass
class DeletionProposal:
    test_id: str
    signals: list[str] = field(default_factory=list)
    blocked_by: str = ""

    @property
    def proposable(self) -> bool:
        """Two independent signals, and not protected."""
        return len(self.signals) >= 2 and not self.blocked_by

    def rationale(self) -> str:
        if self.blocked_by:
            return f"BLOCKED: {self.blocked_by}"
        if len(self.signals) < 2:
            return (
                f"Held back: only {len(self.signals)} signal "
                f"({', '.join(self.signals) or 'none'}). Deletion requires two "
                f"independent signals - low traffic alone is not evidence of death."
            )
        return f"Two independent signals agree this test is obsolete."


def propose_deletions(
    candidates: Sequence[str],
    *,
    registry: ProtectedTestRegistry | None = None,
    zero_traffic: Sequence[str] = (),
    removed_screens: Sequence[str] = (),
    retired_flags: Sequence[str] = (),
) -> list[DeletionProposal]:
    """Apply the dual-signal rule.

    Signal 1 is always "no production traffic on its path". Signal 2 must come from
    somewhere structural - a screen that no longer exists in the taxonomy, or a
    feature flag that has been retired. Without a second signal the test is held
    back, because a path can be absent from a sample for entirely innocent reasons:
    seasonality, a flag rollout, or simply being rare.

    The protected registry overrides everything, whatever the signals say.
    """
    zero = set(zero_traffic)
    screens = set(removed_screens)
    flags = set(retired_flags)

    proposals: list[DeletionProposal] = []
    for test_id in candidates:
        proposal = DeletionProposal(test_id=test_id)

        if test_id in zero:
            proposal.signals.append("no production traffic on its path")
        if any(screen in test_id for screen in screens):
            proposal.signals.append("references a screen removed from the taxonomy")
        if any(flag in test_id for flag in flags):
            proposal.signals.append("guarded by a retired feature flag")

        if registry is not None and registry.is_protected(test_id):
            entry = registry.match(test_id)
            proposal.blocked_by = (
                f"protected under {entry.category.value} by {entry.owner}. "
                f"{entry.reason}"
            )
        proposals.append(proposal)
    return proposals


def deletion_pull_request(
    proposals: Sequence[DeletionProposal],
    *,
    branch: str = "goldenflow/prune-obsolete",
) -> PullRequest:
    """A PR containing only deletions that cleared both the dual-signal rule and
    the registry. Everything else is reported, not proposed."""
    pr = PullRequest(
        title="[GoldenFlow] Proposed removal of obsolete tests",
        branch=branch,
        labels=["goldenflow", "deletion", "needs-review"],
        draft=True,
    )
    for proposal in proposals:
        if not proposal.proposable:
            continue
        pr.changes.append(ProposedChange(
            kind=ChangeKind.DELETE,
            path=proposal.test_id.split("::")[0],
            test_name=proposal.test_id,
            rationale=proposal.rationale(),
            evidence={"signals": proposal.signals},
        ))
    return pr
