// GoldenFlow journey graph
// taxonomy fingerprint: fd24fa23214566d2
CREATE CONSTRAINT screen_id IF NOT EXISTS
  FOR (s:Screen) REQUIRE s.screen_id IS UNIQUE;
CREATE CONSTRAINT journey_id IF NOT EXISTS
  FOR (j:Journey) REQUIRE j.journey_id IS UNIQUE;

MERGE (s:Screen {screen_id: "account_delete"}) SET s.display_name = "Delete Account", s.domain = "account", s.critical = true, s.sensitivity = "high", s.visits = 2, s.entry_count = 0, s.exit_count = 2;
MERGE (s:Screen {screen_id: "account_home"}) SET s.display_name = "Account Home", s.domain = "account", s.critical = false, s.sensitivity = "low", s.visits = 187, s.entry_count = 1, s.exit_count = 2;
MERGE (s:Screen {screen_id: "address_book"}) SET s.display_name = "Address Book", s.domain = "account", s.critical = false, s.sensitivity = "high", s.visits = 20, s.entry_count = 0, s.exit_count = 20;
MERGE (s:Screen {screen_id: "cart"}) SET s.display_name = "Cart", s.domain = "checkout", s.critical = true, s.sensitivity = "none", s.visits = 549, s.entry_count = 0, s.exit_count = 285;
MERGE (s:Screen {screen_id: "category_list"}) SET s.display_name = "Category List", s.domain = "browse", s.critical = false, s.sensitivity = "none", s.visits = 374, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "contact_support"}) SET s.display_name = "Contact Support", s.domain = "support", s.critical = false, s.sensitivity = "low", s.visits = 48, s.entry_count = 0, s.exit_count = 48;
MERGE (s:Screen {screen_id: "data_export"}) SET s.display_name = "Export My Data", s.domain = "account", s.critical = true, s.sensitivity = "high", s.visits = 5, s.entry_count = 0, s.exit_count = 5;
MERGE (s:Screen {screen_id: "delivery_address"}) SET s.display_name = "Delivery Address", s.domain = "checkout", s.critical = true, s.sensitivity = "high", s.visits = 266, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "forgot_password"}) SET s.display_name = "Forgot Password", s.domain = "auth", s.critical = false, s.sensitivity = "high", s.visits = 10, s.entry_count = 0, s.exit_count = 10;
MERGE (s:Screen {screen_id: "help_center"}) SET s.display_name = "Help Center", s.domain = "support", s.critical = false, s.sensitivity = "none", s.visits = 48, s.entry_count = 1, s.exit_count = 0;
MERGE (s:Screen {screen_id: "home"}) SET s.display_name = "Home", s.domain = "browse", s.critical = false, s.sensitivity = "none", s.visits = 1481, s.entry_count = 747, s.exit_count = 177;
MERGE (s:Screen {screen_id: "login"}) SET s.display_name = "Login", s.domain = "auth", s.critical = true, s.sensitivity = "critical", s.visits = 141, s.entry_count = 6, s.exit_count = 0;
MERGE (s:Screen {screen_id: "notification_center"}) SET s.display_name = "Notification Center", s.domain = "account", s.critical = false, s.sensitivity = "low", s.visits = 6, s.entry_count = 0, s.exit_count = 6;
MERGE (s:Screen {screen_id: "onboarding_carousel"}) SET s.display_name = "Onboarding Carousel", s.domain = "auth", s.critical = false, s.sensitivity = "none", s.visits = 45, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "order_confirmation"}) SET s.display_name = "Order Confirmation", s.domain = "checkout", s.critical = true, s.sensitivity = "high", s.visits = 193, s.entry_count = 0, s.exit_count = 193;
MERGE (s:Screen {screen_id: "order_history"}) SET s.display_name = "Order History", s.domain = "account", s.critical = false, s.sensitivity = "high", s.visits = 139, s.entry_count = 0, s.exit_count = 109;
MERGE (s:Screen {screen_id: "order_review"}) SET s.display_name = "Order Review", s.domain = "checkout", s.critical = true, s.sensitivity = "high", s.visits = 193, s.entry_count = 0, s.exit_count = 1;
MERGE (s:Screen {screen_id: "otp_verify"}) SET s.display_name = "OTP Verification", s.domain = "auth", s.critical = true, s.sensitivity = "critical", s.visits = 176, s.entry_count = 0, s.exit_count = 1;
MERGE (s:Screen {screen_id: "payment_failure"}) SET s.display_name = "Payment Failure", s.domain = "checkout", s.critical = true, s.sensitivity = "high", s.visits = 72, s.entry_count = 0, s.exit_count = 72;
MERGE (s:Screen {screen_id: "payment_method"}) SET s.display_name = "Payment Method", s.domain = "checkout", s.critical = true, s.sensitivity = "critical", s.visits = 261, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "product_detail"}) SET s.display_name = "Product Detail", s.domain = "browse", s.critical = false, s.sensitivity = "none", s.visits = 1065, s.entry_count = 1, s.exit_count = 515;
MERGE (s:Screen {screen_id: "product_list"}) SET s.display_name = "Product List", s.domain = "browse", s.critical = false, s.sensitivity = "none", s.visits = 511, s.entry_count = 0, s.exit_count = 1;
MERGE (s:Screen {screen_id: "profile_edit"}) SET s.display_name = "Edit Profile", s.domain = "account", s.critical = false, s.sensitivity = "high", s.visits = 13, s.entry_count = 0, s.exit_count = 13;
MERGE (s:Screen {screen_id: "refund_request"}) SET s.display_name = "Refund Request", s.domain = "support", s.critical = true, s.sensitivity = "high", s.visits = 30, s.entry_count = 0, s.exit_count = 30;
MERGE (s:Screen {screen_id: "saved_cards"}) SET s.display_name = "Saved Cards", s.domain = "account", s.critical = true, s.sensitivity = "critical", s.visits = 9, s.entry_count = 0, s.exit_count = 9;
MERGE (s:Screen {screen_id: "search"}) SET s.display_name = "Search", s.domain = "browse", s.critical = false, s.sensitivity = "low", s.visits = 328, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "signup"}) SET s.display_name = "Sign Up", s.domain = "auth", s.critical = true, s.sensitivity = "critical", s.visits = 45, s.entry_count = 0, s.exit_count = 0;
MERGE (s:Screen {screen_id: "splash"}) SET s.display_name = "Splash", s.domain = "auth", s.critical = false, s.sensitivity = "none", s.visits = 743, s.entry_count = 743, s.exit_count = 0;

MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "home"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 557, r.probability = 0.7497;
MATCH (a:Screen {screen_id: "product_detail"}), (b:Screen {screen_id: "cart"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 548, r.probability = 0.9964;
MATCH (a:Screen {screen_id: "product_list"}), (b:Screen {screen_id: "product_detail"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 510, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "category_list"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 372, r.probability = 0.2853;
MATCH (a:Screen {screen_id: "category_list"}), (b:Screen {screen_id: "product_list"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 370, r.probability = 0.9893;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "product_detail"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 357, r.probability = 0.2738;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "search"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 326, r.probability = 0.2500;
MATCH (a:Screen {screen_id: "cart"}), (b:Screen {screen_id: "delivery_address"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 264, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "delivery_address"}), (b:Screen {screen_id: "payment_method"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 261, r.probability = 0.9812;
MATCH (a:Screen {screen_id: "search"}), (b:Screen {screen_id: "product_detail"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 193, r.probability = 0.5884;
MATCH (a:Screen {screen_id: "order_review"}), (b:Screen {screen_id: "order_confirmation"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 192, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "payment_method"}), (b:Screen {screen_id: "order_review"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 190, r.probability = 0.7280;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "account_home"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 186, r.probability = 0.1426;
MATCH (a:Screen {screen_id: "otp_verify"}), (b:Screen {screen_id: "home"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 175, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "order_history"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 136, r.probability = 0.7351;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "login"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 135, r.probability = 0.1817;
MATCH (a:Screen {screen_id: "search"}), (b:Screen {screen_id: "product_list"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 134, r.probability = 0.4085;
MATCH (a:Screen {screen_id: "login"}), (b:Screen {screen_id: "otp_verify"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 130, r.probability = 0.9220;
MATCH (a:Screen {screen_id: "payment_method"}), (b:Screen {screen_id: "payment_failure"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 70, r.probability = 0.2682;
MATCH (a:Screen {screen_id: "help_center"}), (b:Screen {screen_id: "contact_support"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 48, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "help_center"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 47, r.probability = 0.0360;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "onboarding_carousel"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 45, r.probability = 0.0606;
MATCH (a:Screen {screen_id: "onboarding_carousel"}), (b:Screen {screen_id: "signup"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 44, r.probability = 0.9778;
MATCH (a:Screen {screen_id: "signup"}), (b:Screen {screen_id: "otp_verify"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 44, r.probability = 0.9778;
MATCH (a:Screen {screen_id: "order_history"}), (b:Screen {screen_id: "refund_request"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 30, r.probability = 1.0000;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "address_book"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 20, r.probability = 0.1081;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "profile_edit"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 13, r.probability = 0.0703;
MATCH (a:Screen {screen_id: "login"}), (b:Screen {screen_id: "forgot_password"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 10, r.probability = 0.0709;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "saved_cards"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 9, r.probability = 0.0486;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "product_list"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 7, r.probability = 0.0054;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "notification_center"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 6, r.probability = 0.0046;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "data_export"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 5, r.probability = 0.0270;
MATCH (a:Screen {screen_id: "category_list"}), (b:Screen {screen_id: "product_detail"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 4, r.probability = 0.0107;
MATCH (a:Screen {screen_id: "delivery_address"}), (b:Screen {screen_id: "order_review"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 3, r.probability = 0.0113;
MATCH (a:Screen {screen_id: "home"}), (b:Screen {screen_id: "order_history"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 3, r.probability = 0.0023;
MATCH (a:Screen {screen_id: "delivery_address"}), (b:Screen {screen_id: "payment_failure"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 2, r.probability = 0.0075;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "search"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 2, r.probability = 0.0027;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "category_list"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 2, r.probability = 0.0027;
MATCH (a:Screen {screen_id: "account_home"}), (b:Screen {screen_id: "account_delete"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 2, r.probability = 0.0108;
MATCH (a:Screen {screen_id: "product_detail"}), (b:Screen {screen_id: "delivery_address"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 2, r.probability = 0.0036;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "otp_verify"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0013;
MATCH (a:Screen {screen_id: "onboarding_carousel"}), (b:Screen {screen_id: "otp_verify"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0222;
MATCH (a:Screen {screen_id: "payment_method"}), (b:Screen {screen_id: "order_confirmation"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0038;
MATCH (a:Screen {screen_id: "search"}), (b:Screen {screen_id: "cart"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0030;
MATCH (a:Screen {screen_id: "signup"}), (b:Screen {screen_id: "home"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0222;
MATCH (a:Screen {screen_id: "login"}), (b:Screen {screen_id: "home"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0071;
MATCH (a:Screen {screen_id: "splash"}), (b:Screen {screen_id: "signup"}) MERGE (a)-[r:FOLLOWS]->(b) SET r.weight = 1, r.probability = 0.0013;

MERGE (j:Journey {journey_id: "aj_003"}) SET j.name = "Splash to Purchase", j.score = 95.19, j.sessions = 193, j.rank = 1, j.sequence = ["splash", "home", "search", "product_detail", "cart", "delivery_address", "payment_method", "order_review", "order_confirmation"];
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "search"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "cart"}) MERGE (j)-[st:STEP {position: 4}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "delivery_address"}) MERGE (j)-[st:STEP {position: 5}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "payment_method"}) MERGE (j)-[st:STEP {position: 6}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "order_review"}) MERGE (j)-[st:STEP {position: 7}]->(s);
MATCH (j:Journey {journey_id: "aj_003"}), (s:Screen {screen_id: "order_confirmation"}) MERGE (j)-[st:STEP {position: 8}]->(s);
MERGE (j:Journey {journey_id: "aj_002"}) SET j.name = "Cart Abandonment", j.score = 75.21, j.sessions = 285, j.rank = 2, j.sequence = ["home", "product_detail", "cart"];
MATCH (j:Journey {journey_id: "aj_002"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_002"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_002"}), (s:Screen {screen_id: "cart"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_007"}) SET j.name = "Home to Payment Failure", j.score = 72.48, j.sessions = 72, j.rank = 3, j.sequence = ["home", "product_detail", "cart", "delivery_address", "payment_method", "payment_failure"];
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "cart"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "delivery_address"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "payment_method"}) MERGE (j)-[st:STEP {position: 4}]->(s);
MATCH (j:Journey {journey_id: "aj_007"}), (s:Screen {screen_id: "payment_failure"}) MERGE (j)-[st:STEP {position: 5}]->(s);
MERGE (j:Journey {journey_id: "aj_001"}) SET j.name = "Splash to Product Detail", j.score = 70.00, j.sessions = 381, j.rank = 4, j.sequence = ["splash", "home", "category_list", "product_list", "product_detail"];
MATCH (j:Journey {journey_id: "aj_001"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_001"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_001"}), (s:Screen {screen_id: "category_list"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_001"}), (s:Screen {screen_id: "product_list"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MATCH (j:Journey {journey_id: "aj_001"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 4}]->(s);
MERGE (j:Journey {journey_id: "aj_006"}) SET j.name = "Splash to Home", j.score = 67.14, j.sessions = 131, j.rank = 5, j.sequence = ["splash", "login", "otp_verify", "home"];
MATCH (j:Journey {journey_id: "aj_006"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_006"}), (s:Screen {screen_id: "login"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_006"}), (s:Screen {screen_id: "otp_verify"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_006"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MERGE (j:Journey {journey_id: "aj_009"}) SET j.name = "Splash to Home", j.score = 61.93, j.sessions = 46, j.rank = 6, j.sequence = ["splash", "onboarding_carousel", "signup", "otp_verify", "home"];
MATCH (j:Journey {journey_id: "aj_009"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_009"}), (s:Screen {screen_id: "onboarding_carousel"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_009"}), (s:Screen {screen_id: "signup"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_009"}), (s:Screen {screen_id: "otp_verify"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MATCH (j:Journey {journey_id: "aj_009"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 4}]->(s);
MERGE (j:Journey {journey_id: "aj_005"}) SET j.name = "Home to Product Detail", j.score = 60.58, j.sessions = 134, j.rank = 7, j.sequence = ["home", "search", "product_list", "product_detail"];
MATCH (j:Journey {journey_id: "aj_005"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_005"}), (s:Screen {screen_id: "search"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_005"}), (s:Screen {screen_id: "product_list"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_005"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MERGE (j:Journey {journey_id: "aj_010"}) SET j.name = "Home to Refund Request", j.score = 58.44, j.sessions = 30, j.rank = 8, j.sequence = ["home", "account_home", "order_history", "refund_request"];
MATCH (j:Journey {journey_id: "aj_010"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_010"}), (s:Screen {screen_id: "account_home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_010"}), (s:Screen {screen_id: "order_history"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_010"}), (s:Screen {screen_id: "refund_request"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MERGE (j:Journey {journey_id: "aj_017"}) SET j.name = "Order Review Abandonment", j.score = 57.11, j.sessions = 1, j.rank = 9, j.sequence = ["splash", "home", "search", "product_detail", "cart", "delivery_address", "payment_method", "order_review"];
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "search"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 3}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "cart"}) MERGE (j)-[st:STEP {position: 4}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "delivery_address"}) MERGE (j)-[st:STEP {position: 5}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "payment_method"}) MERGE (j)-[st:STEP {position: 6}]->(s);
MATCH (j:Journey {journey_id: "aj_017"}), (s:Screen {screen_id: "order_review"}) MERGE (j)-[st:STEP {position: 7}]->(s);
MERGE (j:Journey {journey_id: "aj_012"}) SET j.name = "Home to Saved Cards", j.score = 52.73, j.sessions = 9, j.rank = 10, j.sequence = ["home", "account_home", "saved_cards"];
MATCH (j:Journey {journey_id: "aj_012"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_012"}), (s:Screen {screen_id: "account_home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_012"}), (s:Screen {screen_id: "saved_cards"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_004"}) SET j.name = "Home to Order History", j.score = 51.22, j.sessions = 144, j.rank = 11, j.sequence = ["home", "account_home", "order_history"];
MATCH (j:Journey {journey_id: "aj_004"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_004"}), (s:Screen {screen_id: "account_home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_004"}), (s:Screen {screen_id: "order_history"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_014"}) SET j.name = "Home to Export My Data", j.score = 50.15, j.sessions = 5, j.rank = 12, j.sequence = ["home", "account_home", "data_export"];
MATCH (j:Journey {journey_id: "aj_014"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_014"}), (s:Screen {screen_id: "account_home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_014"}), (s:Screen {screen_id: "data_export"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_015"}) SET j.name = "Home to Delete Account", j.score = 46.65, j.sessions = 2, j.rank = 13, j.sequence = ["home", "account_home", "account_delete"];
MATCH (j:Journey {journey_id: "aj_015"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_015"}), (s:Screen {screen_id: "account_home"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_015"}), (s:Screen {screen_id: "account_delete"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_008"}) SET j.name = "Home to Contact Support", j.score = 45.75, j.sessions = 48, j.rank = 14, j.sequence = ["home", "help_center", "contact_support"];
MATCH (j:Journey {journey_id: "aj_008"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_008"}), (s:Screen {screen_id: "help_center"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_008"}), (s:Screen {screen_id: "contact_support"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_011"}) SET j.name = "Splash to Forgot Password", j.score = 43.49, j.sessions = 10, j.rank = 15, j.sequence = ["splash", "login", "forgot_password"];
MATCH (j:Journey {journey_id: "aj_011"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_011"}), (s:Screen {screen_id: "login"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_011"}), (s:Screen {screen_id: "forgot_password"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_013"}) SET j.name = "Home to Notification Center", j.score = 35.93, j.sessions = 6, j.rank = 16, j.sequence = ["home", "notification_center"];
MATCH (j:Journey {journey_id: "aj_013"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_013"}), (s:Screen {screen_id: "notification_center"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MERGE (j:Journey {journey_id: "aj_018"}) SET j.name = "Splash to OTP Verification", j.score = 34.89, j.sessions = 1, j.rank = 17, j.sequence = ["splash", "login", "otp_verify"];
MATCH (j:Journey {journey_id: "aj_018"}), (s:Screen {screen_id: "splash"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_018"}), (s:Screen {screen_id: "login"}) MERGE (j)-[st:STEP {position: 1}]->(s);
MATCH (j:Journey {journey_id: "aj_018"}), (s:Screen {screen_id: "otp_verify"}) MERGE (j)-[st:STEP {position: 2}]->(s);
MERGE (j:Journey {journey_id: "aj_016"}) SET j.name = "Home to Product Detail", j.score = 33.78, j.sessions = 1, j.rank = 18, j.sequence = ["home", "product_detail"];
MATCH (j:Journey {journey_id: "aj_016"}), (s:Screen {screen_id: "home"}) MERGE (j)-[st:STEP {position: 0}]->(s);
MATCH (j:Journey {journey_id: "aj_016"}), (s:Screen {screen_id: "product_detail"}) MERGE (j)-[st:STEP {position: 1}]->(s);
